version: "3.8"
services:
  php-apache-environment:
    container_name: new-php-apache
    build:
      context: ./phpDir
      dockerfile: Dockerfile
    depends_on:
      - newdb
    volumes:
      - ./phpDir/src:/var/www/html/
    ports:
      - 8015:80
  newdb:
    platform: linux/x86_64
    container_name: newdb
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: lionPass
      MYSQL_DATABASE: lionDB
      MYSQL_USER: lionUser
      MYSQL_PASSWORD: lionPass
    ports:
      - "9916:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "9090:80"
    restart: always
    environment:
      PMA_HOST: newdb
    depends_on:
      - newdb
